language: ruby
rvm:
  - 2.0.0-p247

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_install:
  - gem install selenium-webdriver
  - gem install cucumber

script:
- bundle update selenium-webdriver
- bundle exec cucumber --tags @regression --format html --out regression.html --format 'Slowhandcuke::Formatter' BROWSER=firefox LOGIN=test@gmail.com:123456 --tags ~@ignore --guess

notifications:
  email:
   recipients:
    - gireesha21@gmail.com
    - sri@neurlabs.com
    - ptevans@gmail.com
    - saikrishnave38@gmail.com
   on_success: always